name: "CI"

on: [push, pull_request]

jobs:
    tests:
        name: "PHP ${{ matrix.php }} ${{ matrix.mode }}"

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                  - php: '7.3'
                  - php: '7.3'
                    mode: low-deps
                  - php: '7.4'
                  - php: '8.0'
                  - php: '8.1'
                  - php: '8.1'
                    mode: low-deps

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2.3.3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@2.18.0
              with:
                  coverage: "none"
                  php-version: ${{ matrix.php }}
                  tools: composer

            - name: "Validate composer.json"
              run: "composer validate --strict --no-check-lock"

            - name: "Install dependencies"
              run: |
                if [[ "${{ matrix.mode }}" = low-deps ]]; then
                    composer u --prefer-lowest --prefer-stable --ansi
                else
                    composer u --ansi
                fi

            - run: vendor/bin/phpunit

            - if: matrix.php == '8.1' && matrix.mode != 'low-deps'
              name: "Lint PHP files"
              run: vendor/bin/phpcs -ps
